name: Scheduled Weather Images
on:
  schedule:
    - cron: '15 00 * * *'
    - cron: '15 06 * * *'
    - cron: '15 12 * * *'
    - cron: '15 18 * * *'
jobs:

  bot:
    name: bot scheduled weather
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 3.12.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.12.x"
          
      - name: Install pipenv
        run: pip install pipenv

      - name: Install wkhtmltopdf manually
        run: |
          sudo apt-get update
          sudo apt-get install -y xfonts-75dpi libjpeg-turbo8
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
        
      - name: Run forecast for Mad Bna
        run: |
          pipenv install
          pipenv run python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WEEKLY_FORECAST_CHAT_ID: -1002586766682
