name: Test Weather Images
on: [push]
jobs:
  bot:
    name: bot scheduled weather
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxss1 \
            libgtk-3-0 libxshmfence1 libasound2 libgbm1 xvfb

      - name: Install Python dependencies
        run: pipenv install

      - name: Install Playwright browsers
        run: pipenv run playwright install --with-deps

      - name: Run forecast for Mad Bna
        run: pipenv run python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WEEKLY_FORECAST_CHAT_ID: -1002586766682
